// This file exports Material UI icons for use throughout the application
// We're using this approach to avoid having to import MUI icons directly in each file
import React from 'react';

// Import icons from @mui/icons-material
import {
  Dashboard,
  People,
  CleaningServices,
  Build,
  Inventory2,
  Groups,
  Business,
  Psychology,
  AdminPanelSettings,
  Add,
  Search,
  Notifications,
  Person,
  Settings,
  Logout,
  Menu,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  TrendingDown,
  Today,
  Refresh,
  ArrowForward,
  CheckCircle,
  Error,
  Warning,
  ShoppingCart,
  FilterList,
  Delete,
  Edit,
  Check,
  PriorityHigh,
  Schedule,
  Home,
  Phone,
  Email,
  Flag,
  CalendarMonth,
  PhotoCamera,
  Assignment,
  Cancel,
  MapOutlined,
  Engineering,
  Description,
  Business as BusinessIcon,
  AssignmentInd,
  AttachMoney,
  AutoAwesome,
} from '@mui/icons-material';

// Re-export all icons
export {
  Dashboard,
  People,
  CleaningServices,
  Build,
  Inventory2,
  Groups,
  Business,
  Psychology,
  AdminPanelSettings,
  Add,
  Search,
  Notifications,
  Person,
  Settings,
  Logout,
  Menu,
  ChevronLeft,
  ChevronRight,
  TrendingUp,
  TrendingDown,
  Today,
  Refresh,
  ArrowForward,
  CheckCircle,
  Error,
  Warning,
  ShoppingCart,
  FilterList,
  Delete,
  Edit,
  Check,
  PriorityHigh,
  Schedule,
  Home,
  Phone,
  Email,
  Flag,
  CalendarMonth,
  PhotoCamera,
  Assignment,
  Cancel,
  MapOutlined,
  Engineering,
  Description,
  BusinessIcon,
  AssignmentInd,
  AttachMoney,
  AutoAwesome,
};
